/**
 * Session & Artifact Store
 * Manages VR sessions and artifacts
 */

import { v4 as uuid } from 'uuid';
import type { VRSession, GeneratedEpisode, Artifact } from '../types.js';

/**
 * In-memory session store (use Redis/DB in production)
 */
const sessions: Map<string, VRSession> = new Map();

/**
 * Create a new VR session
 * @param userIdOrSessionId - User ID for auto-generated session ID, or explicit session ID if startsWith 'session-'
 * @param episode - The generated episode
 */
export function createSession(userIdOrSessionId: string, episode: GeneratedEpisode): VRSession {
  // Check if explicit session ID was provided
  const isExplicitId = userIdOrSessionId.startsWith('session-');
  const sessionId = isExplicitId ? userIdOrSessionId : uuid();
  const userId = isExplicitId ? 'web-ui' : userIdOrSessionId;
  
  const session: VRSession = {
    id: sessionId,
    userId,
    episode,
    currentScene: 0,
    currentCharacter: 0,
    artifacts: [],
    startedAt: new Date(),
    lastActivity: new Date(),
    status: 'active'
  };
  
  sessions.set(session.id, session);
  return session;
}

/**
 * Get a session by ID
 */
export function getSession(sessionId: string): VRSession | undefined {
  return sessions.get(sessionId);
}

/**
 * Update session state
 */
export function updateSession(
  sessionId: string, 
  updates: Partial<VRSession>
): VRSession | undefined {
  const session = sessions.get(sessionId);
  if (!session) return undefined;
  
  const updated: VRSession = {
    ...session,
    ...updates,
    lastActivity: new Date()
  };
  
  sessions.set(sessionId, updated);
  return updated;
}

/**
 * Add an artifact to a session
 */
export function addArtifact(sessionId: string, artifact: Artifact): VRSession | undefined {
  const session = sessions.get(sessionId);
  if (!session) return undefined;
  
  session.artifacts.push(artifact);
  session.lastActivity = new Date();
  
  return session;
}

/**
 * Advance to next character in sequence
 */
export function advanceCharacter(sessionId: string): VRSession | undefined {
  const session = sessions.get(sessionId);
  if (!session) return undefined;
  
  if (session.currentCharacter < session.episode.characterSequence.length - 1) {
    session.currentCharacter++;
    session.currentScene = session.episode.characterSequence[session.currentCharacter].order;
    session.lastActivity = new Date();
  } else {
    // Reached the end - at playground
    session.status = 'at-playground';
  }
  
  return session;
}

/**
 * Get current character for session
 */
export function getCurrentCharacter(sessionId: string) {
  const session = sessions.get(sessionId);
  if (!session) return undefined;
  
  return session.episode.characterSequence[session.currentCharacter];
}

/**
 * Get current scene for session
 */
export function getCurrentScene(sessionId: string) {
  const session = sessions.get(sessionId);
  if (!session) return undefined;
  
  return session.episode.sceneSequence[session.currentScene];
}

/**
 * Mark session as building (Ralph started)
 */
export function startBuilding(sessionId: string): VRSession | undefined {
  return updateSession(sessionId, { status: 'building' });
}

/**
 * Mark session as complete
 */
export function completeSession(sessionId: string): VRSession | undefined {
  return updateSession(sessionId, { status: 'complete' });
}

/**
 * Get all sessions for a user
 */
export function getUserSessions(userId: string): VRSession[] {
  return Array.from(sessions.values()).filter(s => s.userId === userId);
}

/**
 * Delete a session
 */
export function deleteSession(sessionId: string): boolean {
  return sessions.delete(sessionId);
}

/**
 * Export session artifacts to .springfield folder format
 */
export function exportArtifacts(sessionId: string): Record<string, string> {
  const session = sessions.get(sessionId);
  if (!session) return {};
  
  const files: Record<string, string> = {};
  
  // Create project.md
  files['project.md'] = `# ${session.episode.title}

Problem: ${session.episode.problem.statement}
Domain: ${session.episode.problem.primaryDomain}
Complexity: ${session.episode.problem.complexity}
Generated: ${session.episode.generatedAt.toISOString()}
`;
  
  // Create individual artifact files
  for (const artifact of session.artifacts) {
    const filename = artifact.type.replace('.md', '') + `-${artifact.character}.md`;
    files[filename] = `# ${artifact.title}
Generated by: ${artifact.character}
Scene: ${artifact.scene}
Created: ${artifact.createdAt.toISOString()}

---

${artifact.content}
`;
  }
  
  // Create completion.md
  files['completion.md'] = `# Session Completion

Status: ${session.status}
Characters Consulted: ${session.episode.characterSequence.map(c => c.character).join(', ')}
Total Artifacts: ${session.artifacts.length}
Duration: ${Math.round((session.lastActivity.getTime() - session.startedAt.getTime()) / 60000)} minutes
`;
  
  return files;
}
